/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurReveal: typeof import('./src/components/ui/BlurReveal.vue')['default']
    Button: typeof import('primevue/button')['default']
    CardBody: typeof import('./src/components/ui/card-3d/CardBody.vue')['default']
    CardContainer: typeof import('./src/components/ui/card-3d/CardContainer.vue')['default']
    CardItem: typeof import('./src/components/ui/card-3d/CardItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
